#############################################################################
# Makefile for building: ChickenLauncher
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ??? 15 14:51:07 2017
# Project:  ChickenLauncher.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile ChickenLauncher.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = scr/main.cpp \
		scr/mainwindow.cpp \
		scr/baseconfig.cpp \
		scr/gzdoom.cpp \
		scr/prboom.cpp \
		scr/listsfill.cpp \
		scr/functions.cpp \
		scr/configdialog.cpp \
		scr/colors.cpp moc_mainwindow.cpp \
		moc_configdialog.cpp \
		qrc_icon.cpp
OBJECTS       = main.o \
		mainwindow.o \
		baseconfig.o \
		gzdoom.o \
		prboom.o \
		listsfill.o \
		functions.o \
		configdialog.o \
		colors.o \
		moc_mainwindow.o \
		moc_configdialog.o \
		qrc_icon.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ChickenLauncher.pro
QMAKE_TARGET  = ChickenLauncher
DESTDIR       = 
TARGET        = ChickenLauncher

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_configdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ChickenLauncher.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile ChickenLauncher.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ChickenLauncher.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ChickenLauncher1.0.0 || $(MKDIR) .tmp/ChickenLauncher1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ChickenLauncher1.0.0/ && $(COPY_FILE) --parents scr/mainwindow.h scr/baseconfig.h scr/gzdoom.h scr/prboom.h scr/listsfill.h scr/functions.h scr/configdialog.h scr/colors.h .tmp/ChickenLauncher1.0.0/ && $(COPY_FILE) --parents scr/icon.qrc .tmp/ChickenLauncher1.0.0/ && $(COPY_FILE) --parents scr/main.cpp scr/mainwindow.cpp scr/baseconfig.cpp scr/gzdoom.cpp scr/prboom.cpp scr/listsfill.cpp scr/functions.cpp scr/configdialog.cpp scr/colors.cpp .tmp/ChickenLauncher1.0.0/ && $(COPY_FILE) --parents scr/mainwindow.ui scr/configdialog.ui .tmp/ChickenLauncher1.0.0/ && (cd `dirname .tmp/ChickenLauncher1.0.0` && $(TAR) ChickenLauncher1.0.0.tar ChickenLauncher1.0.0 && $(COMPRESS) ChickenLauncher1.0.0.tar) && $(MOVE) `dirname .tmp/ChickenLauncher1.0.0`/ChickenLauncher1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ChickenLauncher1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_configdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_configdialog.cpp
moc_mainwindow.cpp: scr/baseconfig.h \
		ui_mainwindow.h \
		scr/listsfill.h \
		scr/colors.h \
		scr/gzdoom.h \
		scr/functions.h \
		scr/configdialog.h \
		scr/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) scr/mainwindow.h -o moc_mainwindow.cpp

moc_configdialog.cpp: scr/baseconfig.h \
		ui_mainwindow.h \
		scr/listsfill.h \
		scr/colors.h \
		scr/gzdoom.h \
		scr/functions.h \
		scr/configdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) scr/configdialog.h -o moc_configdialog.cpp

compiler_rcc_make_all: qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp
qrc_icon.cpp: scr/icon.qrc \
		scr/images/rename.svg \
		scr/images/chicken.png \
		scr/images/load.svg \
		scr/images/top.svg \
		scr/images/bottom.svg \
		scr/images/down.svg \
		scr/images/refresh.svg \
		scr/images/new.svg \
		scr/images/clone.svg \
		scr/images/up.svg \
		scr/images/delete.svg \
		scr/images/rename.svg \
		scr/images/chicken.png \
		scr/images/load.svg \
		scr/images/top.svg \
		scr/images/bottom.svg \
		scr/images/down.svg \
		scr/images/refresh.svg \
		scr/images/new.svg \
		scr/images/clone.svg \
		scr/images/up.svg \
		scr/images/delete.svg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name icon scr/icon.qrc -o qrc_icon.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configdialog.h
ui_mainwindow.h: scr/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic scr/mainwindow.ui -o ui_mainwindow.h

ui_configdialog.h: scr/configdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic scr/configdialog.ui -o ui_configdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: scr/main.cpp scr/mainwindow.h \
		scr/baseconfig.h \
		ui_mainwindow.h \
		scr/listsfill.h \
		scr/colors.h \
		scr/gzdoom.h \
		scr/functions.h \
		scr/configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o scr/main.cpp

mainwindow.o: scr/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o scr/mainwindow.cpp

baseconfig.o: scr/baseconfig.cpp scr/baseconfig.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseconfig.o scr/baseconfig.cpp

gzdoom.o: scr/gzdoom.cpp scr/gzdoom.h \
		ui_mainwindow.h \
		scr/baseconfig.h \
		scr/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gzdoom.o scr/gzdoom.cpp

prboom.o: scr/prboom.cpp scr/prboom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prboom.o scr/prboom.cpp

listsfill.o: scr/listsfill.cpp scr/listsfill.h \
		ui_mainwindow.h \
		scr/baseconfig.h \
		scr/colors.h \
		scr/gzdoom.h \
		scr/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listsfill.o scr/listsfill.cpp

functions.o: scr/functions.cpp scr/functions.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o scr/functions.cpp

configdialog.o: scr/configdialog.cpp scr/configdialog.h \
		scr/baseconfig.h \
		ui_mainwindow.h \
		scr/listsfill.h \
		scr/colors.h \
		scr/gzdoom.h \
		scr/functions.h \
		ui_configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o scr/configdialog.cpp

colors.o: scr/colors.cpp scr/colors.h \
		ui_mainwindow.h \
		scr/baseconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colors.o scr/colors.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icon.o qrc_icon.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

